apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-deployment
  namespace: ajay-ns
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers: 
        - name: ecommerce-container
          image: ajaykumar5292/ecommerce-app:v1.0.0
          ports:
            - containerPort: 80